### ISSUE TITLE
关于主题色

### ISSUE THREAD

**Issue by zhou1996-hub** [treadpit/wx_calendar#456]
请问 （ ” 日 一 二 三 四 五 六 “ ） ，字体颜色怎么改变

**Comment by treadpit** [comment]
自行覆盖主题样式文件即可
```css
.default_week-color {
   color: xxx
}

```
